services:
  web:
    image: lenchoreyes/jade:rails-app-${RUBY_VERSION:-4.0}-sqlite-trixie
    stdin_open: true
    tty: true
    user: "dev:dev"
    volumes:
      - .:/home/dev/app
      - dev_home:/home/dev
    environment:
      - SSH_AUTH_SOCK=/ssh-agent
      - NODE_ENV=development
      - BOOTSNAP_CACHE_DIR=/usr/local/bundle/_bootsnap
      - WEB_CONCURRENCY=1
    ports:
      - "3000"
    command: /bin/bash

volumes:
  dev_home:
